### ISSUE TITLE
Downloads page

### ISSUE THREAD

**Issue by alejandrovr** [Acellera/software.acellera.com#11]
- remove "source code for lovers" (it's already on the top bar on the gibhub icon)

- different downloads for different versions (HTMD - stable, latest; ACEMD- 2, 3)

- Downloads simpler and more accessible

- Account for academic and comercial

**Comment by alejandrovr** [comment]
navigation bar - tab highlighting

**Comment by j3mdamas** [comment]
@alejandrovr I published it, but it has no images. Can you check it?

**Comment by alejandrovr** [comment]
Sure! Probably they are not included on the server yet. Thanks!

**Comment by alejandrovr** [comment]
Solved
