### ISSUE TITLE
CSS of code input and outputs

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/software.acellera.com#13]
Following @Acellera/stefan's point here: https://github.com/Acellera/htmd/issues/514#issue-276813871

On any tutorial, the code input and the code output should have a different colouring scheme in order to clearly differentiate them. 

Example: https://software.acellera.com/docs/latest/htmd/tutorials/python-primer.html
![screenshot from 2018-03-15 16-07-17](https://user-images.githubusercontent.com/10810178/37471985-424ee7be-286b-11e8-92f6-a39ea5f66bfa.png)

The first "code block" is code that was run, and the second "code block" is the output of the code. They should look different.

João

**Comment by stefdoerr** [comment]
Yes it used to actually. Something changed at some point and we lost that
markup.

**Comment by alejandrovr** [comment]
I think it can be solved adding:

```
.code.ipython3.highlight-default pre {
    background-color: rgba(208, 212, 215, 0.6);
}
```

to the theme.css. Check for example: https://software.acellera.com/test/docs/latest/htmd/tutorials/htmd-molecules.html 

I will do it Monday at the office.

**Comment by alejandrovr** [comment]
Already pushed. It works on https://software.acellera.com/test/docs/latest/htmd/tutorials/system-building-protein-in-membrane.html and other tutorials. Closing!

**Comment by j3mdamas** [comment]
I think this is still an issue

**Comment by alejandrovr** [comment]
Really? Could you send me an example?

**Comment by j3mdamas** [comment]
![css](https://user-images.githubusercontent.com/10810178/40349327-9c1634c6-5da6-11e8-9191-f6fb68267428.png)
Just taking the first example that appears. I think the color scheme is so similar that is not obvious one is the input and the other the output. I think it wasn't like this in the past?
I think removing syntax coloring on outputs (which makes no sense at all) could be a good start. I don't know if @stefdoerr or @GerardBCN could have any better inputs.

**Comment by alejandrovr** [comment]
Oh, you mean that. Well, we can put any color that we decide.

**Comment by alejandrovr** [comment]
I have been taking a look at some other projects and I could not find any better solution. Syntax highlight does not seem easy to deactivate on the output block. We can try different scheme colors, but other than that, it is probably too hard.

**Comment by GerardBCN** [comment]
Can you try something like:

div.highlight-default:not(.code) div.highlight pre span{ color: #333
!important }

should turn all the answer codes to monocolor #333

2018-05-31 13:54 GMT+02:00 Alejandro Varela Rial <notifications@github.com>:

**Comment by j3mdamas** [comment]
The psi4 team has a python tutorial that looks like a ipynb: http://www.psicode.org/psi4manual/1.1/psiapi.html

They compile sphinx with CMake, I'm not used to it, but in the end I think that they are using this `nbsphinx` to convert the ipynb to rst. Could be worth looking at it: https://nbsphinx.readthedocs.io/en/0.3.3/ (I can't right now)

**Comment by alejandrovr** [comment]
@GerardBCN Thanks! It worked, together with:

```
.highlight-default:not(.code) .highlight pre span{
    color: #333 !important;

}

.highlight-default:not(.code) .highlight pre span{
    font-weight: normal !important;
}

```
displays output in a raw fashion (check https://software.acellera.com/test/docs/latest/htmd/tutorials/python-primer.html) 

I will give it a look @j3mdamas!

**Comment by GerardBCN** [comment]
👌perfect!

2018-05-31 15:20 GMT+02:00 Alejandro Varela Rial <notifications@github.com>:
