### ISSUE TITLE
Feedback tab

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/software.acellera.com#14]
From https://github.com/Acellera/htmd/issues/620

> have a tab from software.acellera.com to provide feedback on the pages
> A user should be able to easily give us feedback all the times

**Comment by alejandrovr** [comment]
Latest version includes a feedback form. You can check at: https://software.acellera.com/test/docs/latest/index.html

**Comment by GerardBCN** [comment]
Can you change the style of the form to:

element.style {

   1. float: left;
   2. padding: 15px;
   3. box-sizing: border-box;
   4. width: 100%;
   5. overflow-x: hidden;

}

2018-04-04 11:50 GMT+02:00 Alejandro Varela Rial <notifications@github.com>:

**Comment by j3mdamas** [comment]
@alejandrovr did you follow gerard's suggestions?

**Comment by alejandrovr** [comment]
Yes, we can close this.
