### ISSUE TITLE
auto auto summary is broken

### ISSUE THREAD

**Issue by giadefa** [Acellera/software.acellera.com#16]
Ask joao

**Comment by j3mdamas** [comment]
https://software.acellera.com/docs/latest/htmd/htmd.molecule.molecule.html

autoautosummary in methods and attributes is broken. maybe it was a wrong publishing. Can you check it @alejandrovr? thanks!

**Comment by alejandrovr** [comment]
Apparently, this is caused by version 1.7.0 of Sphinx changing the definition of the function:

```get_documenter``` 

http://www.sphinx-doc.org/en/stable/changes.html?highlight=get_Documenter

Function which we use in the conf.py file. I will check how to use the new function.

**Comment by alejandrovr** [comment]
I switched to 1.6.6 and autosummary works again. I will spend some time soon trying to adapt conf.py to 1.7.x.
