### ISSUE TITLE
track down where searchtools.js is coming from

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/software.acellera.com#17]

**Comment by alejandrovr** [comment]
Apparently, it is an issue caused by Sphinx version greater than 1.8.0 https://github.com/rtfd/sphinx_rtd_theme/pull/672/commits/4b9053cb9e805211f227399d66d82361b3e2bf56. 

commit 1615585c849069cf1ac63ec5c9080a04440bda56 should solve it

**Comment by j3mdamas** [comment]
thanks @alejandrovr
