### ISSUE TITLE
Navigation Bar collapses to a scrollbar at some levels

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/software.acellera.com#8]
![screenshot from 2017-07-06 14-55-44](https://user-images.githubusercontent.com/10810178/27912073-d0255946-625b-11e7-970c-557fdd19e2e3.png)

The navigation bar gains a scrollbar if the content of the page is too small?

**Comment by j3mdamas** [comment]
did you publish it? I see the same issue still

**Comment by j3mdamas** [comment]
Ok, I will publish it asap.

For reference, fixed here: 42de117fdf53b09bdb144821fa776ae469260013

**Comment by j3mdamas** [comment]
Open again

**Comment by j3mdamas** [comment]
this is still an issue. @alejandrovr can it be solved? if it can't, I'll ignore it and let's close it.

**Comment by alejandrovr** [comment]
I tried to solve it in different ways but all of them cause trouble somewhere else. We can close it.
